class exception:
    def fun():
      try:
        n1=int(input("Enter the first number:"))
        n2=int(input("Enter the second number:"))
        n3=n1/n2
        print(n3)
      except Exception:
        print("Error")
    
ob=exception
ob.fun()
      
